### ISSUE TITLE
Everything is working just fine it seems

### ISSUE THREAD

**Issue by zrocklive** [Koseng/RaspiAsUSBStickWithCloudSync#2]
Everything looks like its running fine but never see the transfer from the transfer directory to my nas. I followed your tutorial to a T and am just wanting to see if you know why this would be happening?

when I check the logs for usb_copy... it shows the blink folders and sub folders even the .mp4 files, but then it sends to the transfer directory, then disappears.

**Comment by zrocklive** [comment]
Here's the log

2024-05-26 17:47:30,250 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:47:30,254 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:47:31,062 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:47:31,064 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:47:31,919 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:47:31,921 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:47:32,752 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:47:32,753 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:47:33,613 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:47:33,615 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:51:06,149 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:51:06,150 [MainThread  ] [ERROR]  Invalid \escape: line 8 column 6                                                                                                                                                             0 (char 306)
Traceback (most recent call last):
  File "/home/pi/copy_new_usb_files.py", line 135, in <module>
    config = json.load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 8 column 60 (char 306)
2024-05-26 17:55:08,241 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:55:08,242 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 17:55:08,332 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 17:55:50,967 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/03-54-35_FrontLanai_003.mp4 to /home/pi/transfer/1716782147/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 17:56:07,106 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/03-54-49_FrontLanai_004.mp4 to /home/pi/transfer/1716782163/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 17:56:23,247 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/03-55-04_FrontLanai_005.mp4 to /home/pi/transfer/1716782180/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 17:56:42,389 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/03-55-21_FrontLanai_006.mp4 to /home/pi/transfer/1716782200/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 17:57:39,787 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 17:57:39,792 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 17:57:40,091 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:01:07,600 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/.tmp/m                                                                                                                                                             r_tmp_file_0 to /home/pi/transfer/1716782467/blink/.tmp
2024-05-26 18:01:07,604 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/.tmp/m                                                                                                                                                             r_tmp_file_1 to /home/pi/transfer/1716782467/blink/.tmp
2024-05-26 18:01:18,844 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:01:18,850 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:01:19,160 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:01:41,911 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/.tmp/m                                                                                                                                                             r_tmp_file_0 to /home/pi/transfer/1716782500/blink/.tmp
2024-05-26 18:01:59,807 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-00-16_FrontLanai_001.mp4 to /home/pi/transfer/1716782503/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:03:00,956 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-02-51_FrontLanai_002.mp4 to /home/pi/transfer/1716782578/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:03:20,098 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-03-08_FrontLanai_003.mp4 to /home/pi/transfer/1716782598/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:03:45,254 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-03-31_FrontLanai_004.mp4 to /home/pi/transfer/1716782623/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:04:04,401 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-03-46_FrontLanai_005.mp4 to /home/pi/transfer/1716782642/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:04:20,729 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:04:20,734 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:04:21,023 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:09:18,084 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-09-10_FrontLanai_001.mp4 to /home/pi/transfer/1716782957/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:18:14,872 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:18:14,876 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:18:15,156 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:19:03,760 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-18-49_FrontLanai_001.mp4 to /home/pi/transfer/1716783542/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:19:25,915 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-19-06_FrontLanai_002.mp4 to /home/pi/transfer/1716783562/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:20:45,069 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-20-29_FrontDoor_003.mp4 to /home/pi/transfer/1716783643/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:20:45,087 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-20-21_FrontLanai_004.mp4 to /home/pi/transfer/1716783643/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:20:49,585 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:20:49,586 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:20:49,593 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:21:01,219 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-20-36_FrontLanai_005.mp4 to /home/pi/transfer/1716783659/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:21:02,184 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-20-36_FrontLanai_005.mp4 to /home/pi/transfer/1716783661/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:21:17,344 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-20-49_FrontLanai_006.mp4 to /home/pi/transfer/1716783675/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:21:33,491 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-02_FrontLanai_007.mp4 to /home/pi/transfer/1716783691/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:21:40,847 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:21:40,849 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:21:40,855 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:21:49,627 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-15_FrontLanai_008.mp4 to /home/pi/transfer/1716783707/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:21:50,447 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-15_FrontLanai_008.mp4 to /home/pi/transfer/1716783709/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:05,772 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-28_FrontLanai_009.mp4 to /home/pi/transfer/1716783723/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:06,602 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-28_FrontLanai_009.mp4 to /home/pi/transfer/1716783725/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:21,901 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-41_FrontLanai_010.mp4 to /home/pi/transfer/1716783739/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:22,745 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-41_FrontLanai_010.mp4 to /home/pi/transfer/1716783741/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:38,041 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-56_FrontLanai_011.mp4 to /home/pi/transfer/1716783756/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:38,911 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-21-56_FrontLanai_011.mp4 to /home/pi/transfer/1716783758/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:55,071 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-10_FrontLanai_012.mp4 to /home/pi/transfer/1716783773/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:22:57,170 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-10_FrontLanai_012.mp4 to /home/pi/transfer/1716783775/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:19,294 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-33_FrontLanai_013.mp4 to /home/pi/transfer/1716783798/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:20,235 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-33_FrontLanai_013.mp4 to /home/pi/transfer/1716783799/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:35,441 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-46_FrontLanai_014.mp4 to /home/pi/transfer/1716783814/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:36,412 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-22-46_FrontLanai_014.mp4 to /home/pi/transfer/1716783815/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:51,592 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-23-01_FrontLanai_015.mp4 to /home/pi/transfer/1716783830/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:23:52,571 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-23-01_FrontLanai_015.mp4 to /home/pi/transfer/1716783831/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:25:08,854 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-25-01_FrontLanai_016.mp4 to /home/pi/transfer/1716783908/blink/24-05                                                                                                                                                             /24-05-27
2024-05-26 18:25:19,011 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-25-05_Carport_017.mp4 to /home/pi/transfer/1716783916/blink/24-05/24                                                                                                                                                             -05-27
2024-05-26 18:29:18,389 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:29:18,395 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:29:18,701 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:38:32,792 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-38-13_BackLanai_001.mp4 to /home/pi/transfer/1716784709/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:39:18,941 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-38-57_BackLanai_002.mp4 to /home/pi/transfer/1716784757/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:40:08,097 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-39-42_BackLanai_003.mp4 to /home/pi/transfer/1716784804/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:40:39,239 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-40-11_BackLanai_004.mp4 to /home/pi/transfer/1716784836/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:41:01,393 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-40-31_BackLanai_005.mp4 to /home/pi/transfer/1716784858/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:42:36,680 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-42-04_BackLanai_006.mp4 to /home/pi/transfer/1716784954/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:43:16,800 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-42-42_BackLanai_007.mp4 to /home/pi/transfer/1716784994/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:44:35,924 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-43-59_BackLanai_008.mp4 to /home/pi/transfer/1716785074/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:46:04,063 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-45-24_BackLanai_009.mp4 to /home/pi/transfer/1716785163/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:47:23,214 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/04-46-39_BackLanai_010.mp4 to /home/pi/transfer/1716785240/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 18:49:02,551 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:49:02,556 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:49:02,852 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:58:21,232 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:58:21,236 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:58:21,534 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 18:59:50,723 [MainThread  ] [INFO ]  ----STARTED copy_new_usb_files.p                                                                                                                                                             y----
2024-05-26 18:59:50,725 [MainThread  ] [INFO ]  Configuration loaded.
2024-05-26 18:59:50,732 [MainThread  ] [INFO ]  Loop Device: /dev/loop0p1
2024-05-26 19:03:22,318 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/05-02-29_BackLanai_001.mp4 to /home/pi/transfer/1716786201/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 19:03:56,470 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/05-03-00_BackLanai_002.mp4 to /home/pi/transfer/1716786235/blink/24-05/                                                                                                                                                             24-05-27
2024-05-26 19:04:18,614 [MainThread  ] [INFO ]  Copy /mnt/usb_share/blink/24-05/                                                                                                                                                             24-05-27/05-04-03_FrontDoor_003.mp4 to /home/pi/transfer/1716786257/blink/24-05/                                                                                                                                                             24-05-27

**Comment by zrocklive** [comment]
I am gonna try this:

def copy_new_files(last_modify_time, device):
    current_modify_time = os.stat(USB_IMG).st_mtime
    if (current_modify_time > last_modify_time[0]):
        mount(device, SOURCE_DIR)
        
        # Create the destination directory if it doesn't exist
        destination_dir = os.path.join(DESTINATION_BASE_DIR, str(int(current_modify_time)))
        os.makedirs(destination_dir, exist_ok=True)  # This is the added line

        new_files = get_files_since_point_in_time(SOURCE_DIR, last_modify_time[0], newest_dir_count=2)
        Path(COPYING_ACTIVE_FILE).touch()
        for file in new_files:
            copy_file_with_directory_structure(SOURCE_DIR, file, destination_dir)
        if os.path.isfile(COPYING_ACTIVE_FILE):
            os.remove(COPYING_ACTIVE_FILE)
        umount(SOURCE_DIR)
        last_modify_time[0] = os.stat(USB_IMG).st_mtime

**Comment by feenx** [comment]
I'm having a similar issue when using SCP option. It seems the way `transfer_via_scp` is called within `upload_new_files.py` if `transfer_via_scp` errors, it's ignored and the following `removeTree` function is still called, deleting the files even if the transfer failed.

Came here hoping someone else had the same issue, and knew more about the ".exp" bits. Calling the SCP command manually seems to work fine.
