### ISSUE TITLE
InvalidAccessToken

### ISSUE THREAD

**Issue by Dennis-Otto** [Koseng/RaspiAsUSBStickWithCloudSync#3]
I am getting the following error:

2024-07-29 14:21:01,066 [MainThread  ] [INFO ]  ----STARTED upload_new_files.py----
2024-07-29 14:21:01,073 [MainThread  ] [INFO ]  Configuration loaded.
2024-07-29 14:21:01,080 [MainThread  ] [INFO ]  START UPLOAD Path: /System Volume Information/IndexerVolumeGuid
2024-07-29 14:21:01,088 [MainThread  ] [INFO ]  Refreshing access token.
2024-07-29 14:21:02,932 [MainThread  ] [ERROR]  AuthError('4302cf9bf2d848aeb55dbebea22201ac', AuthError('invalid_access_token', None))
Traceback (most recent call last):
  File "/home/pi/upload_new_files.py", line 82, in <module>
    transfer_to_dropbox(folder, config)
  File "/home/pi/upload_new_files.py", line 59, in transfer_to_dropbox
    file_metadata = dbx.files_upload(f.read(), destination_path, mode=WriteMode('overwrite'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dropbox/base.py", line 3208, in files_upload
    r = self.request(
        ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dropbox/dropbox_client.py", line 304, in request
    self.check_and_refresh_access_token()
  File "/usr/lib/python3/dist-packages/dropbox/dropbox_client.py", line 372, in check_and_refresh_access_token
    self.refresh_access_token(scope=self._scope)
  File "/usr/lib/python3/dist-packages/dropbox/dropbox_client.py", line 406, in refresh_access_token
    self.raise_dropbox_error_for_resp(res)
  File "/usr/lib/python3/dist-packages/dropbox/dropbox_client.py", line 628, in raise_dropbox_error_for_resp
    raise AuthError(request_id, err)
dropbox.exceptions.AuthError: AuthError('4302cf9bf2d848aeb55dbebea22201ac', AuthError('invalid_access_token', None))

I created the App in Drobox as described in the ReadMe and placed the AppKey, AppSecret and RefreshToken to the config.json.
Is there anything I missed?

**Comment by Dennis-Otto** [comment]
I resolved it by manually getting the refreshToken as described in these two articles:
https://developers.dropbox.com/de-de/oauth-guide
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Get-refresh-token-from-access-token/td-p/596739

@Koseng The refreshToken you output with the DropboxHelper is not correct. You are returning the account_id, not the refresh_token

**Comment by Koseng** [comment]
@DennisOtto-dev thanks for letting me know. Currently I have no time to take care, but I'll return to the project at some point and fix it.
